version: 2.1

orbs:
  node: circleci/node@3.0.0

# Jobs definition
jobs:
  run_tests_with_coverage:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npx jest --ci --runInBand
      - run: npx codecov --token="${CODECOV_TOKEN}"

workflows:
   version: 2
   run_tests_with_coverage_report:
     jobs:
       - run_tests_with_coverage

